# Specifica la porta (cambiala per ogni server, es. 8443, 8081, 8082...)
server.port=8080


# Database
spring.datasource.url=jdbc:mysql://localhost:3306/progetto_GPO
spring.datasource.username=root
spring.datasource.password=

# Metti validate(controlla che ci siano gia le tabelle) o update(crea/aggiorna tabelle)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Token
jwt.secret=VGhpc0lzQVNlY3JldEtleUZvckpXVFRlc3QxMjM0NTY=